Warrior:
  measure: reward
  thresholds: [0.8, 1.0, 1.2, 1.2, 1.2, 1.2,1.2,1.2]
  min_lesson_length: 100
  signal_smoothing: true
  parameters:
    move_speed: [4.0, 5.0, 5.0, 5.0, 6.0, 6.0, 6.0, 6.0, 6.0]
    attack_range: [10.0, 9.0, 8.0, 7.0, 6.0, 5.0, 4.0, 3.0, 2.0]